Feature/add jest testing
MrRamoun/mathCalc pull request #6
Opened 2022-02-17 17:26 UTC by MrRamoun

- ✔️ Set up React Testing Library.
- ✔️ Follow the instructions in the official documentation.
- ✔️ Write unit tests for the files `operate.js` and `calculate.js` using Jest.
- ✔️ Create unit tests for all React components.
- ✔️ Use Jest snapshots to test the components.
- ✔️ Use React Testing Library to simulate user interaction.
- ✔️ Run your full tests suite using Jest. All tests passed.

2022-02-17 18:12 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @MrRamoun and @fherrerao,

Good job so far!
✔️ Use of React Testing Library
✔️ Tests cover most operations
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 18:12 UTC, TedLivist commented on README.md
> +
- [ ] For proper documentation, in your README kindly add the command for running the tests.

2022-02-17 19:00 UTC, BrianSammit approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello team 👋, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![Well-Done-Applause](https://user-images.githubusercontent.com/64173189/154551893-05720e39-2925-4c64-a486-22c82d48bf51.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 04:40 UTC, MrRamoun commented on README.md
> +
Thank you so much 👍

2022-02-18 04:40 UTC, merged